name: Fermus
favicon: null
layout_spectrum: 0.19704
typography_spectrum: 0
title: Betatesting the grid
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#00b9fe'
    - '#3f3f3f'
    - '#000000'
    - '#00ffff'
    - '#0080ff'
  brandStrength: 0.375
  lightness: 0.5
  saturation: 0.4375
  rhythmicContrast: 1
purpose: []
