name: Fermus
favicon: null
layout_spectrum: 0.79448
typography_spectrum: 0.38038
title: Fermus
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#050402'
    - '#fefefe'
    - '#791d28'
    - '#606465'
    - '#fd2a45'
  brandStrength: 0.3813477859366685
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
