layout_spectrum: 0.447230031808912
typography_spectrum: 0.06771467276563001
color:
  brandColors:
    - '#170F0E'
    - '#290418'
    - '#505217'
    - '#FFD372'
    - '#FFF1AF'
  brandStrength: 0.5392242195381608
  lightness: 0.621638762090392
  saturation: 0.3415023232686638
  rhythmicContrast: 0.8501026419853551
coverPrefs:
  filter: false
name: Daniel Ferm
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/af9c2bc0-010a-4c39-a22a-a9067dd01d32.png
cta: {}
analytics: {}
opengraph:
  type: ''
  appId: ''
purpose:
  - type: contact
    label: Call me
    url: 'tel:46735622800'
  - type: contact
    label: Mail me
    url: 'mailto:info@fermedia.se'
title: Developer of magic things
description: >-
  This is my personal log as a Dad, hard working web-designer and life-magician.
  Do not take all things i write or quote here seriously. 
author:
  name: Daniel Ferm
  url: fermus.sw
  email: info@fermedia
content_rating:
  adult: false
content: []
github: true
