analytics: {}
color:
  brandColors:
    - '#B8C8D8'
    - '#000000'
    - '#687898'
    - '#000000'
    - '#000000'
  brandStrength: 0.558558
  lightness: 0.5
  rhythmicContrast: 0.5
  saturation: 0.5
cta: {}
layout_spectrum: 0.549549
name: Fermus
opengraph: {}
purpose: []
typography_spectrum: 0.877252
