name: Fermus
favicon: null
layout_spectrum: 0.2778706680983305
typography_spectrum: 0.6276149689219892
title: Fermus
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ff0000'
    - '#e68000'
    - '#000000'
    - '#aa5500'
    - '#808000'
  brandStrength: 0.3813477859366685
  lightness: 0.1875
  saturation: 0.125
  rhythmicContrast: 1
purpose: []
