name: Fermus
favicon: null
layout_spectrum: 1
typography_spectrum: 1
title: Daniel Ferms blogg
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f9faff'
    - '#181715'
    - '#afc1d5'
    - '#ce9683'
    - '#586986'
  brandStrength: 0.5
  lightness: 0.8125
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
