name: Fermus
favicon: null
layout_spectrum: 0.65817
typography_spectrum: 1
title: Daniel Ferms blogg
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#00b9fe'
    - '#3f3f3f'
    - '#000000'
    - '#00ffff'
    - '#0080ff'
  brandStrength: 0.1875
  lightness: 0.8125
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
