name: Fermus
favicon: null
layout_spectrum: 0.2778706680983305
typography_spectrum: 0.6276149689219892
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.3813477859366685
  lightness: 0.5407168003730476
  saturation: 0.5083707254379988
  rhythmicContrast: 0.4462286427151412
purpose: []
